### ISSUE TITLE
How you do day5 part2?

### ISSUE THREAD

**Issue by sekift** [maxnoe/aoc23#1]
Look at day5 & part2, the true seeds is:
seeds: 1263068588 44436703 1116624626 2393304 2098781025 128251971 2946842531 102775703 2361566863 262106125 221434439 24088025 1368516778 69719147 3326254382 101094138 1576631370 357411492 3713929839 154258863
and then:
221434439 24088025
1116624626 2393304
1263068588 44436703
1368516778 69719147
1576631370 357411492
2098781025 128251971
2361566863 262106125
2946842531 102775703
3326254382 101094138
3713929839 154258863
The range of seeds is 1246535471(sum)，How can you get the right answer of it? Some optimize the loop?

**Comment by maxnoe** [comment]
The code in this repo is what I used. I started thinking about a clever solution, but the bruteforce approach finished in around 6 minutes, way before I managed to find a better one.
